---
version: "{build}"
  
environment:
  matrix:
    - JAVA_HOME: "C:\Program Files\Java\jdk1.8.0"
    - JAVA_HOME: "C:\Program Files\Java\jdk11"
    - JAVA_HOME: "C:\Program Files\Java\jdk12"
    - JAVA_HOME: "C:\Program Files\Java\jdk13"

install:
- cmd: git clone --depth 3 https://github.com/loc-rdc/bagit-conformance-suite.git

branches:
  except:
  - crowdin_translations

build_script:
- cmd: ./gradlew.bat check --no-daemon

shallow_clone: true

cache:
  - '%USERPROFILE%\.gradle'

notifications:
- provider: Email
  to:
  - john.scancella@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true